"use client";

import { useState } from "react";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { usePolicyExplanation } from "@/hooks/useData";
import { RefreshCw, Sparkles, AlertCircle, Clock, Lightbulb, ShieldAlert, BarChart2, GitFork } from "lucide-react";

interface ExplainDrawerProps {
  draftId: string;
  open: boolean;
  onClose: () => void;
}

function ExplainSection({ icon: Icon, title, content }: { icon: React.ElementType; title: string; content: string }) {
  return (
    <div className="space-y-2">
      <div className="flex items-center gap-2 text-sm font-semibold text-foreground">
        <Icon className="w-4 h-4 text-primary" />
        {title}
      </div>
      <p className="text-sm text-muted-foreground leading-relaxed bg-muted/50 rounded-lg p-3">
        {content}
      </p>
    </div>
  );
}

function ExplainSkeleton() {
  return (
    <div className="space-y-6">
      {[1, 2, 3, 4].map((i) => (
        <div key={i} className="space-y-2">
          <Skeleton className="h-4 w-32" />
          <Skeleton className="h-16 w-full rounded-lg" />
        </div>
      ))}
    </div>
  );
}

export function ExplainDrawer({ draftId, open, onClose }: ExplainDrawerProps) {
  const [refreshKey, setRefreshKey] = useState(0);
  const { data, loading, error } = usePolicyExplanation(open ? draftId : null);
  const explanation = data?.explanation ?? null;

  const handleRefresh = () => setRefreshKey((k) => k + 1);

  return (
    <Sheet open={open} onOpenChange={(v) => !v && onClose()}>
      <SheetContent className="w-full sm:max-w-xl overflow-y-auto">
        <SheetHeader className="space-y-2">
          <SheetTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-blue-500" />
            AI Policy Explanation
          </SheetTitle>
          <SheetDescription>
            Generated by the local LLM. Describes why this policy was suggested and its expected impact.
          </SheetDescription>
        </SheetHeader>

        <div className="mt-6 space-y-6">
          {loading ? (
            <ExplainSkeleton />
          ) : error || !explanation ? (
            <div className="rounded-xl border border-dashed border-muted-foreground/30 p-6 text-center space-y-3">
              <Clock className="w-8 h-8 mx-auto text-muted-foreground/50" />
              <p className="text-sm font-medium text-foreground">
                Explanation not ready yet
              </p>
              <p className="text-xs text-muted-foreground">
                The LLM is still generating the explanation. This usually takes 20–40 seconds after the draft was created.
              </p>
              <Button
                size="sm"
                variant="outline"
                className="rounded-lg"
                onClick={handleRefresh}
              >
                <RefreshCw className="w-3 h-3 mr-1.5" />
                Check again
              </Button>
            </div>
          ) : (
            <>
              <ExplainSection
                icon={AlertCircle}
                title="Explanation"
                content={explanation.explanation}
              />
              <ExplainSection
                icon={ShieldAlert}
                title="Severity Reasoning"
                content={explanation.severityReasoning}
              />
              <ExplainSection
                icon={Lightbulb}
                title="Policy Reasoning"
                content={explanation.policyReasoning}
              />
              <ExplainSection
                icon={BarChart2}
                title="Estimated Impact"
                content={explanation.estimatedImpact}
              />

              {explanation.alternatives.length > 0 && (
                <div className="space-y-2">
                  <div className="flex items-center gap-2 text-sm font-semibold text-foreground">
                    <GitFork className="w-4 h-4 text-primary" />
                    Alternative Approaches
                  </div>
                  <ul className="space-y-2">
                    {explanation.alternatives.map((alt, i) => (
                      <li key={i}>
                        <Badge
                          variant="outline"
                          className="rounded-lg text-xs font-normal py-1.5 px-3 h-auto whitespace-normal text-left"
                        >
                          {alt}
                        </Badge>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </>
          )}
        </div>
      </SheetContent>
    </Sheet>
  );
}
